### ISSUE TITLE
Near term checklist

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/libnd4j#443]
Few things still missing in new NDArray concept and classes related to it:

- [ ] non-inplace permute/reshape/transpose
- [ ] reference tracking for views/TADs/whatever
- [ ] workspaces
- [ ] more static factory methods (and move existing NDArray constructors there)
- [ ] more helpers for debugging/profiling
- [ ] CUDA
